{% set name = "proxsuite" %}
{% set version = "0.2.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Simple-Robotics/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: a65ca85ba8f5431759948ab99905623d53ed5026c4e5f70297a0aedfbc2bbfb9

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}  # [not win]
    - vs2017_win-64  # [win64]
    - vs2017_win-32  # [win32]
    - cmake
    - clang  # [win]
    - make  # [not win]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - simde
    - doxygen
  host:
    - eigen
    - python
    - simde
  run:
    - eigen
    - python
    - scipy
    - numpy
    - simde

test:
  imports:
    - proxsuite
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/simple-robotics/proxsuite
  summary: Quadratic Programming Solver for Robotics and beyond.
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/simple-robotics/proxsuite

extra:
  recipe-maintainers:
    - fabinsch
    - jcarpent
    - Bambade
